[package]
name = "naive_linalg"
version = "0.1.0"
authors = ["fatirishman53"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "~1.1"